/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User.ts'

/**
 * @description successful operation
 */
export type CreateUsersWithArrayInputError = any

/**
 * @description List of user object
 */
export type CreateUsersWithArrayInputMutationRequest = User[]

export type CreateUsersWithArrayInputMutationResponse = any

export type CreateUsersWithArrayInputMutation = {
  Response: any
  Request: CreateUsersWithArrayInputMutationRequest
  Errors: any
}